py -m pip install  pip==23.2
py -m pip install  akshare
py -m pip install  easyquotation
py -m pip install  yagmail
py -m pip install  pywinauto==0.6.6
py -m pip install  matplotlib
py -m pip install  mplfinance
py -m pip install  finta
py -m pip install  pyinstaller
py -m pip install  pyautogui
py -m pip install  schedule
py -m pip install  pywin32
py -m pip install  pyexecjs
py -m pip install  pytdx
py -m pip install  pydash
py -m pip install  empyrical
py -m pip install  pywencai 
py -m pip install  pandas==1.5.3
py -m pip install  numpy==1.26.2
py -m pip install  scipy==1.11.4
py -m pip install  ffn
py -m pip install  quantstats==0.0.60
py -m pip install  dash