py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pip==23.2
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ akshare
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ easyquotation
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ yagmail
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pywinauto==0.6.6
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ matplotlib
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ mplfinance
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ finta
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pyinstaller
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pyautogui
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ schedule
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pywin32
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pyexecjs
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pytdx
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pydash
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ empyrical
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pywencai 
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ pandas==1.5.3
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ numpy==1.26.2
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ scipy==1.11.4
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ ffn
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ quantstats==0.0.60
py -m pip install -i https://mirrors.aliyun.com/pypi/simple/ dash