py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip==23.2
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple akshare
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple easyquotation
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple yagmail
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pywinauto==0.6.6
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple matplotlib
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple mplfinance
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple finta
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyinstaller
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyautogui
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple schedule
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pywin32
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyexecjs
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pytdx
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pydash
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple empyrical
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pywencai 
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas==1.5.3
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numpy==1.26.2
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple scipy==1.11.4
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple ffn
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple quantstats==0.0.60
py -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple dash